### ISSUE TITLE
More Detail?

### ISSUE THREAD

**Issue by Lego2build** [sonya75/apekyc#1]
Would it be easy to add 915+, 1220+, 1525+ to your list so folks can estimate how many mints there will be through the process? Thanks!

**Comment by sonya75** [comment]
I only added 305, 610 and 1830 because I assume people who can't afford to buy all the ape coins beforehand will dump their lands during first wave to prepare for second wave.

**Comment by Dreeze1** [comment]
Thank you so much for this !
I would also love to see the number of holders of 915+, 1220+, 1525+ $ape if this is possible ? 🙏

**Comment by sonya75** [comment]
Added.
