### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by 0xVinx** [sonya75/apekyc#2]
1) are the addresses in wallet.csv all the KYCed addresses? meaning there are no more addresses which kyced so total no. is ~40k?
2) when you say `305+: 12508` does this include people who have 610+? meaning if `610+: 8993` and 8993 people mint two, then are there additional 12.5k people who can mint one or 12.5k - 8993?

thanks!

**Comment by sonya75** [comment]
yeah, 305+ includes 610+. The full list is in the wallets.csv file also.

There are no more active addresses that KYCed, only around 41k. Any address that has been active in the last 2 months is in that file and when they get active now before the drop, they get added in the file automatically.
